version: "3.7"

services:
  http:
    container_name: grpc-http
    build: http
    command: /main
    ports:
      - 3000:3000
    depends_on:
      - search
  search:
    container_name: grpc-search
    build: search
    command: /main
    ports:
      - 1000:1000
    depends_on:
      - es
  es:
    container_name: grpc-es
    image: elasticsearch:8.2.3
    ports:
      - 9200:9200